version: '3.3'

services:
  backend:
    build: ./backend
    container_name: aero-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: h2
    restart: on-failure

  frontend:
    build: ./frontend
    container_name: aero-frontend
    ports:
      - "3000:80"
    environment:
      PORT: 80
      BACKEND_URL: http://backend:8080
    depends_on:
      - backend
    restart: on-failure
